---

- name: Fail if required semaphore settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - semaphore_hostname
    - semaphore_admin_password
    - semaphore_admin_name
    - semaphore_admin_email
    - semaphore_access_key_encryption
